default: &default
  adapter: postgresql
  encoding: unicode
  database: expenses
  pool: 5
  username: postgres
  password: 1234

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default